### ISSUE TITLE
datetime feature engineering issues

### ISSUE THREAD

**Issue by hadisotudeh** [microsoft/FLAML#284] opened 2021-11-17 15:19 UTC
Hi,

Below, you can see the error I face:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-13-268d18d5ce5d> in <module>()
     33   train_pred_proba = best.predict_proba(xs)[:,1]
     34   performance["training (auc_roc)"] = calc_auc_roc(y, train_pred_proba)
---> 35   validation_pred_proba = best.predict_proba(valid_xs)[:,1]
     36   performance["validation (auc_roc)"]  = calc_auc_roc(valid_y, validation_pred_proba)
     37   performance_list.append(performance)

5 frames
/usr/local/lib/python3.7/dist-packages/flaml/automl.py in predict_proba(self, X_test)
    478             (i, j) is the probability for instance i to be in class j.
    479         """
--> 480         X_test = self._preprocess(X_test)
    481         proba = self._trained_estimator.predict_proba(X_test)
    482         return proba

/usr/local/lib/python3.7/dist-packages/flaml/automl.py in _preprocess(self, X)
    490             X = X.tocsr()
    491         if self._transformer:
--> 492             X = self._transformer.transform(X)
    493         return X
    494 

/usr/local/lib/python3.7/dist-packages/flaml/data.py in transform(self, X)
    379                     X[column] = X[column].map(datetime.toordinal)
    380                     del tmp_dt
--> 381             X = X[cat_columns + num_columns].copy()
    382             if self._task == TS_FORECAST:
    383                 X.insert(0, TS_TIMESTAMP_COL, ds_col)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py in __getitem__(self, key)
   2910             if is_iterator(key):
   2911                 key = list(key)
-> 2912             indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
   2913 
   2914         # take() does not accept boolean indexers

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _get_listlike_indexer(self, key, axis, raise_missing)
   1252             keyarr, indexer, new_indexer = ax._reindex_non_unique(keyarr)
   1253 
-> 1254         self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
   1255         return keyarr, indexer
   1256 

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1302             if raise_missing:
   1303                 not_found = list(set(key) - set(ax))
-> 1304                 raise KeyError(f"{not_found} not in index")
   1305 
   1306             # we skip the warning on Categorical

KeyError: "['month_search_date', 'quarter_search_date'] not in index"

```

It seems the datetime features are not created for the validation set. I assumed using best.predict_proba will apply the same pipeline to the validation set, which was fitted with the training set.

Any idea?

**Comment by sonichi** [comment] 2021-11-17 16:32
@hadisotudeh I've found a possible root cause and I'm working on a fix. It'll be helpful if you could provide a simple test example that reproduces this error.

**Comment by hadisotudeh** [comment] 2021-11-17 16:45
I can share the google colab notebook link if you provide your email address, but I can't put it here for the public :)

**Comment by sonichi** [comment] 2021-11-17 18:13
@hadisotudeh I just sent an empty private notebook to you and transferred the ownership to you: https://colab.research.google.com/drive/1KfYI3oSPAz6E3IlXZyhytHhDe47dvNwa?usp=sharing

**Comment by hadisotudeh** [comment] 2021-11-17 18:37
Thanks, I put the code there. If you select "Run all". You can see where the expectation appears. I think I also found another issue with fast automl model.fit() gets out of memory and crashes while I set the memory threshold below the maximum available. You can also see that issue, too.

**Comment by sonichi** [comment] 2021-11-18 04:04
@hadisotudeh #285 fixes the error.
While xgboost fails in the colab notebook, it succeeded with larger RAM size.
flaml is capable of handling datasets with more than 10 million rows, as long as the estimators in the estimator_list do not fail.

**Comment by hadisotudeh** [comment] 2021-11-18 08:01
Great news.
Should I update the package with "pip install" or just use the changes you made to the code?

**Comment by sonichi** [comment] 2021-11-18 08:32
The pypi package has not been released yet. You can clone the "issue284" branch and do `pip install -e.` to install the cloned version to test it.

**Closed** 2021-11-18 19:19 UTC
